title: Gustavo Coelho
description: > # this means to ignore newlines until "baseurl:"
  Data Science Blog to share insights about what I am learning.
  Main interests include Machine Learning, Game Theory and Mechanism Design.
  This blog is mostly in Portuguese to help spread DS knowledge among Portuguese speakers.
  
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gusrabbit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url_share: "http://gusrabbit.com"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gustavo Coelho
author-img: gustavo-coelho.jpg # add your photo
about-author: I am a Data Scientist with background in economics in search for interesting algorithms and insights. # add description
twitter: gusrabbit
facebook: gustavosfcoelho
github: gusrabbit 
linkedin: gusrabbit 
email: gustavosfcoelho@gmail.com 

# Disqus
discus-identifier: gusrabbit

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
